# -*- coding: utf-8 -*-
"""カロリーキング.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdNiYY1I92qOUtxBOGCqrDZbdv5qGEwk
"""

import streamlit as st
import random

# --- 1. クイズデータの設定 ---
# 料理名, 分量(g), カロリー(kcal)
FOOD_DATA = [
    {"food": "白米", "weight": "250g", "calories": 390},
    {"food": "牛丼", "weight": "400g", "calories": 730},
    {"food": "野菜炒め", "weight": "250g", "calories": 180},
    {"food": "鶏の唐揚げ（5個）", "weight": "150g", "calories": 450},
    {"food": "味噌ラーメン", "weight": "600g", "calories": 550},
    {"food": "ハンバーグステーキ", "weight": "200g", "calories": 450},
    {"food": "カレーライス", "weight": "500g", "calories": 850},
    {"food": "焼き魚（ホッケ）", "weight": "200g", "calories": 220},
    {"food": "ポテトサラダ", "weight": "120g", "calories": 210},
    {"food": "とんかつ", "weight": "150g", "calories": 500},
]

# --- 2. セッション状態の初期化 ---
if "history" not in st.session_state:
    st.session_state.history = []  # 全解答履歴
if "wrong_indices" not in st.session_state:
    st.session_state.wrong_indices = set()  # 間違えた問題のインデックス（重複なし）
if "current_question" not in st.session_state:
    st.session_state.current_question = random.choice(FOOD_DATA)

# --- 3. アプリの構成 ---
st.title("🍽️ 料理カロリー当てクイズ")
st.caption("一般成人男性の1食分程度の分量で出題します")

menu = st.sidebar.selectbox("メニュー", ["クイズに挑戦", "復習モード", "解答履歴と傾向"])

# --- 関数：回答チェック ---
def check_answer(user_val, correct_val, food_info):
    # 誤差±10%以内なら正解とする（数値入力の場合の配慮）
    is_correct = abs(user_val - correct_val) <= (correct_val * 0.1)

    result = {
        "料理": food_info["food"],
        "分量": food_info["weight"],
        "あなたの回答": f"{user_val} kcal",
        "正解": f"{correct_val} kcal",
        "判定": "⭕ 正解" if is_correct else "❌ 不正解"
    }

    st.session_state.history.append(result)

    if not is_correct:
        # 間違えた料理の名前を復習リストに追加
        st.session_state.wrong_indices.add(food_info["food"])
        st.error(f"残念！正解は {correct_val} kcal でした。")
    else:
        st.success(f"正解です！ ({correct_val} kcal)")

    # 次の問題へ
    st.session_state.current_question = random.choice(FOOD_DATA)

# --- モード1：通常クイズ ---
if menu == "クイズに挑戦":
    q = st.session_state.current_question
    st.subheader(f"問題：{q['food']}（{q['weight']}）のカロリーは？")

    user_input = st.number_input("予想カロリー(kcal)を入力", min_value=0, step=10, key="normal_quiz")

    if st.button("回答する"):
        check_answer(user_input, q["calories"], q)

# --- モード2：復習モード ---
elif menu == "復習モード":
    st.subheader("📝 過去に間違えた問題")

    if not st.session_state.wrong_indices:
        st.info("現在、復習が必要な問題はありません。素晴らしい！")
    else:
        # 間違えた料理のデータだけを抽出
        review_list = [f for f in FOOD_DATA if f["food"] in st.session_state.wrong_indices]
        q_review = random.choice(review_list)

        st.write(f"再挑戦：**{q_review['food']}（{q_review['weight']}）**")
        user_input_review = st.number_input("予想カロリー(kcal)を入力", min_value=0, step=10, key="review_quiz")

        if st.button("回答する"):
            # 正解したら復習リストから削除
            is_correct = abs(user_input_review - q_review["calories"]) <= (q_review["calories"] * 0.1)
            if is_correct:
                st.session_state.wrong_indices.remove(q_review["food"])
                st.success("復習成功！リストから削除されました。")

            check_answer(user_input_review, q_review["calories"], q_review)

# --- モード3：履歴表示 ---
elif menu == "解答履歴と傾向":
    st.subheader("📊 これまでの解答履歴")
    if st.session_state.history:
        st.table(st.session_state.history)
        if st.button("履歴をリセット"):
            st.session_state.history = []
            st.session_state.wrong_indices = set()
            st.rerun()
    else:
        st.write("まだ履歴がありません。")